package by.training.finance.controller.command;

public enum CommandType {
	
	SIGN_IN, SIGN_OUT, REGISTER, DELETE,
	ADD_ACCOUNT, REMOVE_ACCOUNT, ADD_CATEGORY, REMOVE_CATEGORY, BALANCE, PAY, RECEIPT, SHOW_INFO,
	ALL_PAYMENTS, FULL_SUM, ALL_PAYMENTS_BETWEEN_DATES,
	WROND_COMMAND

}
